package profile

import (
	"context"

	"cloud.google.com/go/firestore"

	"tsunagg/backend/model/chat"
	"tsunagg/backend/model/db"
)

// メッセージを投稿する
func SendMessage(ctx context.Context, c *firestore.Client, p *db.AutoGenerated, uuid string, channel string) error {
	api, err := chat.NewSlackUserClient(ctx, c, uuid)
	if err != nil {
		return err
	}

	msg := createMessage(p)

	info, exists, err := getMessageInfo(ctx, c, uuid)
	if err != nil {
		return err
	}

	if exists {
		// 既に投稿済みの場合はメッセージを更新
		_, _, _, err := api.UpdateMessageContext(ctx, info.ChannelId, info.Timestamp, msg)
		if err != nil {
			return err
		}
	} else {
		// 初投稿の場合は投稿⇒メッセージ情報を登録
		channelId, ts, err := api.PostMessageContext(ctx, channel, msg)
		if err != nil {
			return err
		}

		if err := registerMessageInfo(ctx, c, uuid, channelId, ts); err != nil {
			return err
		}
	}
	return nil
}
