package chat

import (
	"context"
	"errors"

	"cloud.google.com/go/firestore"
	"github.com/slack-go/slack"

	"tsunagg/backend/model/db"
)

// メッセージを投稿する
func SendMessage(ctx context.Context, c *firestore.Client, p *db.AutoGenerated, uuid string, channel string) error {
	token, err := getSlackAPIToken(ctx, c, uuid)
	if err != nil {
		return err
	}
	api := slack.New(token)

	msg := createMessage(p)

	info, exists, err := getMessageInfo(ctx, c, uuid)
	if err != nil {
		return err
	}

	if exists {
		// 既に投稿済みの場合はメッセージを更新
		_, _, _, err := api.UpdateMessageContext(ctx, info.ChannelId, info.Timestamp, msg)
		if err != nil {
			return err
		}
	} else {
		// 初投稿の場合は投稿⇒メッセージ情報を登録
		channelId, ts, err := api.PostMessageContext(ctx, channel, msg)
		if err != nil {
			return err
		}

		if err := registerMessageInfo(ctx, c, uuid, channelId, ts); err != nil {
			return err
		}
	}
	return nil
}

func getSlackAPIToken(ctx context.Context, c *firestore.Client, uuid string) (string, error) {
	dsnap, err := c.Collection("users").Doc(uuid).Get(ctx)
	if err != nil {
		return "", err
	}

	token, err := dsnap.DataAt("OAuthToken")
	if err != nil {
		return "", err
	}

	tokenStr, ok := token.(string)
	if !ok {
		return "", errors.New("`OAuthToken` cannot be casted to string")
	}

	return tokenStr, nil
}
